// Generated by Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface NSArray (SWIFT_EXTENSION(Plug))
- (BOOL)validateJSON;
@end


@interface NSArray (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSData * _Nullable jsonData;
@end


@interface NSDictionary (SWIFT_EXTENSION(Plug))
- (BOOL)validateJSON;
@end


@interface NSDictionary (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSData * _Nullable jsonData;
@end


@interface NSError (SWIFT_EXTENSION(Plug))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PlugJSONErrorDomain;)
+ (NSString * _Nonnull)PlugJSONErrorDomain SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isCancelledError;
@property (nonatomic, readonly) BOOL isTimeoutError;
@end


@interface NSMutableDictionary (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull stringDictionary;
@end


@interface NSNull (SWIFT_EXTENSION(Plug))
@end


@interface NSNumber (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * _Nullable jsonString;
@end


@interface NSString (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * _Nullable jsonString;
@end

@class NSOperationQueue;
@class NSURLSessionConfiguration;
@class NSURLSession;

SWIFT_CLASS("_TtC4Plug4Plug")
@interface Plug : NSObject <NSURLSessionDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Plug * _Nonnull instance;)
+ (Plug * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL online;)
+ (BOOL)online SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL autostartConnections;
@property (nonatomic, copy) NSURL * _Nonnull temporaryDirectoryURL;
- (NSURL * _Nonnull)generateTemporaryFileURL SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) NSOperationQueue * _Nonnull sessionQueue;
@property (nonatomic, readonly, strong) NSURLSessionConfiguration * _Nonnull configuration;
@property (nonatomic, strong) NSURLSession * _Null_unspecified session;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull libraryDirectoryURL;)
+ (NSURL * _Nonnull)libraryDirectoryURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull plugDirectoryURL;)
+ (NSURL * _Nonnull)plugDirectoryURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nonnull autoAcceptCredentialsFrom;)
+ (NSArray<NSString *> * _Nonnull)autoAcceptCredentialsFrom SWIFT_WARN_UNUSED_RESULT;
+ (void)setAutoAcceptCredentialsFrom:(NSArray<NSString *> * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)didBecomeActive;
+ (void)attemptReconnectionWithCompletion:(void (^ _Nullable)(void))completion;
@property (nonatomic, readonly) BOOL areConnectionsInFlight;
- (void)rebuildSession;
- (void)setOnlineViaWifi:(BOOL)wifi orWAN:(BOOL)wan;
- (void)updateChannelStates;
@property (nonatomic, strong) NSOperationQueue * _Nonnull serialQueue;
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end

@class NSURLSessionDataTask;
@class NSURLSessionDownloadTask;
@class NSURLSessionTask;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface Plug (SWIFT_EXTENSION(Plug)) <NSURLSessionTaskDelegate, NSURLSessionDownloadDelegate, NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end


@interface NSURLResponse (SWIFT_EXTENSION(Plug))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PlugHTTPErrorDomain;)
+ (NSString * _Nonnull)PlugHTTPErrorDomain SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) NSError * _Nullable error;
@end

#pragma clang diagnostic pop
