// Generated by Apple Swift version 1.2 (swiftlang-602.0.49.3 clang-clang-602.0.49)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import Foundation.NSURLSession;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURLResponse;
@class NSOperationQueue;
@class NSURL;
@class NSURLRequest;
@class NSDate;

SWIFT_CLASS("_TtCC4Plug4Plug10Connection")
@interface Connection : NSObject
@property (nonatomic) NSURLRequestCachePolicy cachingPolicy;
@property (nonatomic) NSURLResponse * __nullable response;
@property (nonatomic) NSOperationQueue * __nullable completionQueue;
@property (nonatomic, readonly) NSURL * __nonnull URL;
@property (nonatomic) BOOL downloadToFile;
@property (nonatomic) NSURLRequest * __nullable request;
@property (nonatomic, readonly) NSOperationQueue * __nonnull requestQueue;
@property (nonatomic) NSDate * __nullable startedAt;
@property (nonatomic) NSDate * __nullable completedAt;
@property (nonatomic, readonly) NSTimeInterval elapsedTime;
- (void)notifyPersistentDelegateOfCompletion;
@end

@class NSData;
@class NSError;

@interface Connection (SWIFT_EXTENSION(Plug))
- (SWIFT_NULLABILITY(nonnull) instancetype)completion:(void (^ __nonnull)(NSData * __nonnull))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)error:(void (^ __nonnull)(NSError * __nonnull))completion;
@end

@class NSDictionary;

@interface Connection (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly) NSDictionary * __nonnull JSONRepresentation;
- (SWIFT_NULLABILITY(nullable) instancetype)initWithJSONRepresentation:(NSDictionary * __nonnull)info;
@end


@interface Connection (SWIFT_EXTENSION(Plug))
- (void)queue;
- (void)start;
- (void)suspend;
- (void)resume;
- (void)cancel;
@end


@interface Connection (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy, getter=description) NSString * __nonnull description;
- (NSString * __nonnull)detailedDescriptionWithIncludeDelimiters:(BOOL)includeDelimiters;
- (void)logErrorToFileWithLabel:(NSString * __nonnull)label;
- (void)log;
@end


@interface NSArray (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * __nullable JSONString;
@end


@interface NSData (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * __nullable JSONString;
@end


@interface NSDictionary (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * __nullable JSONString;
@end


@interface NSMutableDictionary (SWIFT_EXTENSION(Plug))
@end


@interface NSNumber (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * __nullable JSONString;
@end


@interface NSString (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy) NSString * __nullable JSONString;
@end


@interface NSURL (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly) NSURL * __nullable URL;
@end


@interface NSURLRequest (SWIFT_EXTENSION(Plug))
@property (nonatomic, readonly, copy, getter=description) NSString * __nonnull description;
@end


@interface NSURLResponse (SWIFT_EXTENSION(Plug))
+ (NSString * __nonnull)PlugHTTPErrorDomain;
@property (nonatomic, readonly) NSError * __nullable error;
@end


SWIFT_CLASS("_TtC4Plug24NetworkActivityIndicator")
@interface NetworkActivityIndicator : NSObject
+ (void)increment;
+ (void)decrement;
- (void)hideIndicator;
+ (BOOL)isVisible;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSessionConfiguration;
@class NSURLSession;

SWIFT_CLASS("_TtC4Plug4Plug")
@interface Plug : NSObject
+ (Plug * __nonnull)defaultManager;
@property (nonatomic) BOOL autostartConnections;
@property (nonatomic) NSURL * __nonnull temporaryDirectoryURL;
@property (nonatomic) NSOperationQueue * __nonnull sessionQueue;
@property (nonatomic) NSURLSessionConfiguration * __nonnull configuration;
@property (nonatomic) NSURLSession * __null_unspecified session;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface Plug (SWIFT_EXTENSION(Plug)) <NSURLSessionDataDelegate>
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end


@interface Plug (SWIFT_EXTENSION(Plug))
@end

@class NSURLSessionDownloadTask;
@class NSURLSessionTask;
@class NSHTTPURLResponse;

@interface Plug (SWIFT_EXTENSION(Plug)) <NSURLSessionDownloadDelegate>
- (void)URLSession:(NSURLSession * __nonnull)session downloadTask:(NSURLSessionDownloadTask * __nonnull)downloadTask didFinishDownloadingToURL:(NSURL * __nonnull)location;
- (void)URLSession:(NSURLSession * __nonnull)session task:(NSURLSessionTask * __nonnull)task didCompleteWithError:(NSError * __nullable)error;
- (void)URLSession:(NSURLSession * __nonnull)session task:(NSURLSessionTask * __nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * __nonnull)response newRequest:(NSURLRequest * __nonnull)request completionHandler:(void (^ __nonnull)(NSURLRequest * __null_unspecified))completionHandler;
@end

#pragma clang diagnostic pop
